#version: '3.9'

services:
#  nginx:
#    container_name: nginx-server
#    image: nginx:1.29-alpine
#    network_mode: bridge # host、bridge、overlay、none
#    restart: unless-stopped # use always when prod,
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /Users/niuhesong/DevSpaces/Yudao/yudao-ui-admin-vue3/dist:/usr/share/nginx/html
#    environment:
#      - TZ=Asia/Shanghai
#    logging:
#      driver: json-file
#      options:
#        max-size: '1g'
#        max-file: '5'
#    #depends_on:
#    #  - xxx

  redis:
    container_name: redis-server
    image: redis:7.2-alpine
    network_mode: bridge # host、bridge、overlay、none
    restart: unless-stopped # use always when prod,
    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../workspace/data/redis:/data/:rw
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: '1g'
        max-file: '5'
    #depends_on:
    #  - xxx

  mysql:
    container_name: mysql-server
    image: mysql:8.0.34
    network_mode: bridge # host、bridge、overlay、none
    restart: unless-stopped # use always when prod,
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../workspace/config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ../../workspace/data/mysql:/var/lib/mysql/:rw
      - ../../workspace/logs/mysql:/var/log/mysql/:rw
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: '1g'
        max-file: '5'
    #depends_on:
    #  - xxx

#  xxl-job-admin:
#    platform: linux/arm64 # Target platform to run on, e.g., 'linux/amd64', 'linux/arm64', or 'windows/amd64'.
#    container_name: xxl-job-admin
#    image: arm64v8/eclipse-temurin:17-jre
#    network_mode: bridge # host、bridge、overlay、none #!!!host模式，直接访问宿主机
#    restart: unless-stopped # use always when prod,
#    ports:
#      - 8080:8080
#    volumes:
#      - ./xxl-job-admin-3.2.0.jar:/work/app.jar
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      #- SPRING_PROFILES_ACTIVE=prod
#      - TZ=Asia/Shanghai
#      - "spring.datasource.url=jdbc:mysql://db:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
#      - spring.datasource.username=root
#      - spring.datasource.password=123456
#    working_dir: /work
#    logging:
#      driver: json-file
#      options:
#        max-size: '1g'
#        max-file: '5'
#    links:
#      - mysql:db
#    depends_on:
#      - mysql
#    command: ["java","-jar","app.jar"]

  nacos:
    container_name: nacos-standalone
    image: nacos/nacos-server:v2.5.1
    network_mode: bridge # host、bridge、overlay、none
    restart: unless-stopped # use always when prod,
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../workspace/data/nacos:/home/nacos/data:rw
      #- ../../workspace/logs/nacos:/home/nacos/logs
    ports:
      - 8848:8848 #service node
      - 9848:9848 #gRPC
    logging:
      driver: json-file
      options:
        max-size: '1g'
        max-file: '5'