#version: '3.9'

services:
  minio:
    container_name: minio-server
    #image: sha256:b9292014cabd5a53687fa875af1c5527cd34c34d540088e6371b37cd046c542f
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    network_mode: bridge # host、bridge、overlay、none
    restart: unless-stopped # use always when prod,
    ports:
      - 9000:9000 # api
      - 9001:9001 # console
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MINIO_ROOT_USER=admin       # MINIO_ROOT_USER length should be at least 3
      - MINIO_ROOT_PASSWORD=12345678  # MINIO_ROOT_PASSWORD length at least 8 characters
      - MINIO_VOLUMES=/data
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: '1g'
        max-file: '5'
    #depends_on:
    #  - xxx
    command: server /data --console-address ':9001'