#version: '3.9'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.26.10-community  # 使用官方镜像
    environment:
      # 基础配置
      - NEO4J_AUTH=neo4j/12345678  # 默认用户 neo4j，密码 your_password（生产环境请修改）A password must be at least 8 characters
      #- NEO4J_dbms_memory_heap_max__size=2G  # 限制 JVM 堆内存
      #- NEO4J_dbms_memory_pagecache_size=1G  # 限制页面缓存
      # 可选：禁用认证（仅限开发环境）
      # - NEO4J_AUTH=none
    ports:
      - 7474:7474  # HTTP 接口（浏览器访问）
      - 7687:7687  # Bolt 协议（客户端连接）
    volumes:
      - neo4j_data:/data  # 持久化数据（包含数据库、日志等）
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import  # 导入目录（用于 CSV 导入）
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import: