#version: '3.9'

services:
  nginx:
    container_name: nginx-server
    image: nginx:1.29-alpine
    network_mode: bridge # host、bridge、overlay、none
    restart: unless-stopped # use always when prod,
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: '1g'
        max-file: '5'
    #depends_on:
    #  - xxx