#version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine  # 使用带管理插件的官方镜像
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin     # 默认用户名
      - RABBITMQ_DEFAULT_PASS=123456 # 默认密码
      - RABBITMQ_DEFAULT_VHOST=/        # 默认虚拟主机
      #- RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_PLUGINS_ENABLED=rabbitmq_management
    ports:
      - 5672:5672 # AMQP 协议端口
      - 15672:15672 # 管理插件端口
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # 持久化数据目录
      #- ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro  # 可选：自定义配置文件
      #- ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro # 可选：插件配置
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:
    driver: local

networks:
  rabbitmq_network:
    driver: bridge