#version: '3.9'

services:
  mongo:
    container_name: mongo-server
    image: mongo:8.0
    network_mode: bridge # host、bridge、overlay、none
    restart: unless-stopped # use always when prod,
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ../../workspace/data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=test
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: '1g'
        max-file: '5'
    #depends_on:
    #  - xxx
    command: mongod --auth